baseURL = 'https://onkbaonk.github.io/Oonk/'
languageCode = 'en-us'
title = 'Blog Oonk'
theme = 'ananke'

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Semua Artikel"
  url = "/posts/"
  weight = 2

[[menu.main]]
  name = "Tentang Saya"
  url = "/about/"
  weight = 3
  
[params]
  background_color_class = 'bg-black'
