[module.hugoVersion]
min = "0.146.0"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 10

[[menu.main]]
  name = "Arsip"
  url = "/posts/"
  weight = 20

[[menu.main]]
  name = "Tentang Saya"
  url = "/about/"
  weight = 30
