backend:
  name: git-gateway
  branch: main

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "blog"
    label: "Artikel"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Judul", name: "title", widget: "string"}
      - {label: "Tanggal", name: "date", widget: "datetime"}
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - {label: "Isi Konten", name: "body", widget: "markdown"}
      - label: "Kategori"
        name: "categories"
        widget: "select"
        multiple: true
        options: ["Cerita", "Teknologi", "Hobi", "Catatan"]
